[package]
name = "planar"
version = "0.1.0"
edition = "2024"
authors = ["Landon Gingerich <landon.ging@gmail.com>"]
description = "Transaction-based open table format"
readme = "README.md"
repository = "https://github.com/lgingerich/planar"

[dependencies]
arrow = "57.1.0"
arrow-array = "57.1.0"
lance = "1.0.1"
parquet = "57.1.0"
sqlx = "0.8.6"
thiserror = "2.0.17"
vortex = "0.56.0"

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
incremental = false
opt-level = 3
lto = true
panic = "abort"
strip = "debuginfo"

[profile.dev]
codegen-units = 256
debug = 2
debug-assertions = true
incremental = true
opt-level = 0
lto = false
panic = "unwind"
strip = false

[lints.clippy]
type_complexity = "allow"
redundant_clone = "warn"
unnecessary_to_owned = "warn"
inefficient_to_string = "warn"
large_enum_variant = "warn"
box_collection = "warn"
or_fun_call = "warn"
expect_fun_call = "warn"
single_char_pattern = "warn"
string_add_assign = "warn"
vec_init_then_push = "warn"
expect_used = "deny"
unwrap_used = "deny"
