[package]
name = "planar"
version = "0.1.0"
edition = "2024"
authors = ["Landon Gingerich <landon.ging@gmail.com>"]
description = "Transaction-based open table format"
readme = "README.md"
repository = "https://github.com/lgingerich/planar"

[dependencies]
arrow = "56.2.0"
arrow-array = "56.2.0"
arrow-ipc = "56.2.0"
async-trait = "0.1.89"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
lance = "1.0.1"
parquet = { version = "56.2.0", features = ["arrow"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = ["chrono", "migrate", "runtime-tokio-rustls", "sqlite", "postgres"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
thiserror = "2.0.17"
uuid = { version = "1.10", features = ["serde"] }
uuid7 = "1.4.0"
vortex = { version = "0.56.0", features = ["tokio"] }

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
incremental = false
opt-level = 3
lto = true
panic = "abort"
strip = "debuginfo"

[profile.dev]
codegen-units = 256
debug = 2
debug-assertions = true
incremental = true
opt-level = 0
lto = false
panic = "unwind"
strip = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("sqlite", "postgres"))'] }
missing_docs = "warn"

[lints.clippy]
type_complexity = "allow"
redundant_clone = "warn"
unnecessary_to_owned = "warn"
inefficient_to_string = "warn"
large_enum_variant = "warn"
box_collection = "warn"
or_fun_call = "warn"
expect_fun_call = "warn"
single_char_pattern = "warn"
string_add_assign = "warn"
vec_init_then_push = "warn"
expect_used = "deny"
unwrap_used = "deny"
