from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence


class PlanarError(Exception):
    ...


class CatalogError(PlanarError):
    ...


class StorageError(PlanarError):
    ...


class TableIdent:
    namespace: str
    name: str

    def __init__(self, namespace: str, name: str) -> None: ...


class ColumnSpec:
    def __init__(self, name: str, dtype_spec: Dict[str, Any]) -> None: ...
    def nullable(self) -> None: ...


class SchemaSpec:
    def __init__(self) -> None: ...
    def with_column(self, column: ColumnSpec) -> None: ...


class FileSpec:
    def __init__(
        self,
        file_format: str,
        file_path: str,
        record_count: int,
        file_size_bytes: int,
        format_options: Optional[Dict[str, Any]] = ...,
    ) -> None: ...
    def with_partition_values(self, values: Dict[str, Any]) -> None: ...


class Catalog:
    @classmethod
    def in_memory(cls) -> Catalog: ...
    @classmethod
    def from_connection_string(cls, connection_string: str) -> Catalog: ...
    def create_table(
        self,
        ident: TableIdent,
        location: str,
        schema: SchemaSpec,
        properties: Optional[Dict[str, Any]] = ...,
    ) -> TableHandle: ...
    def load_table(self, ident: TableIdent) -> Optional[TableHandle]: ...
    def list_tables(self, namespace: Optional[str] = ...) -> List[TableIdent]: ...
    def drop_table(self, ident: TableIdent) -> None: ...


class TableHandle:
    def read(self) -> Dict[str, Any]: ...
    def read_at(self, transaction_id: str) -> Dict[str, Any]: ...
    def current_transaction_id(self) -> str: ...
    def list_transaction_events(
        self, to_transaction_id: str, from_transaction_id_exclusive: Optional[str] = ...
    ) -> List[Dict[str, Any]]: ...
    def diff(self, from_transaction_id: str, to_transaction_id: str) -> Dict[str, Any]: ...
    def append_file(self, file: FileSpec) -> Dict[str, Any]: ...
    def append_files(self, files: Sequence[FileSpec]) -> Dict[str, Any]: ...
    def delete_files(self, file_uuids: Sequence[str]) -> Dict[str, Any]: ...
    def set_properties(self, properties: Dict[str, Any]) -> Dict[str, Any]: ...


def read_parquet_ipc(path: str, batch_size: Optional[int] = ...) -> bytes: ...
def read_parquet_stream_ipc(path: str, batch_size: Optional[int] = ...) -> bytes: ...
def write_parquet_ipc(path: str, data: bytes, options: Optional[Dict[str, Any]] = ...) -> None: ...
def write_parquet_stream_ipc(
    path: str, data: bytes, options: Optional[Dict[str, Any]] = ...
) -> None: ...

def read_lance_ipc(
    path: str,
    batch_size: Optional[int] = ...,
    columns: Optional[List[str]] = ...,
    filter: Optional[str] = ...,
    limit: Optional[int] = ...,
    offset: Optional[int] = ...,
    scan_in_order: Optional[bool] = ...,
    io_buffer_size: Optional[int] = ...,
) -> bytes: ...
def read_lance_stream_ipc(
    path: str,
    batch_size: Optional[int] = ...,
    columns: Optional[List[str]] = ...,
    filter: Optional[str] = ...,
    limit: Optional[int] = ...,
    offset: Optional[int] = ...,
    scan_in_order: Optional[bool] = ...,
    io_buffer_size: Optional[int] = ...,
) -> bytes: ...
def write_lance_ipc(path: str, data: bytes, options: Optional[Dict[str, Any]] = ...) -> None: ...
def write_lance_stream_ipc(
    path: str, data: bytes, options: Optional[Dict[str, Any]] = ...
) -> None: ...

def read_vortex_ipc(
    path: str,
    initial_read_size: Optional[int] = ...,
    segment_cache: Optional[bool] = ...,
) -> bytes: ...
def read_vortex_stream_ipc(
    path: str,
    initial_read_size: Optional[int] = ...,
    segment_cache: Optional[bool] = ...,
) -> bytes: ...
def write_vortex_ipc(path: str, data: bytes, options: Optional[Dict[str, Any]] = ...) -> None: ...
def write_vortex_stream_ipc(
    path: str, data: bytes, options: Optional[Dict[str, Any]] = ...
) -> None: ...
