from __future__ import annotations

from typing import Any, Iterable, Iterator, List, Optional


class DataType:
    byte_width: int
    unit: str
    tz: Optional[str]
    bit_width: int
    precision: int
    scale: int
    value_field: Field
    list_size: int

    def __iter__(self) -> Iterator[Field]: ...


class Field:
    name: str
    nullable: bool
    type: DataType


class RecordBatch:
    schema: Any


class Table:
    @staticmethod
    def from_batches(batches: Iterable[RecordBatch]) -> Table: ...
    def combine_chunks(self) -> Table: ...
    def to_batches(self) -> List[RecordBatch]: ...


class Buffer:
    def to_pybytes(self) -> bytes: ...


class BufferOutputStream:
    def __init__(self) -> None: ...
    def getvalue(self) -> Buffer: ...


class RecordBatchStreamWriter:
    def write(self, batch: RecordBatch) -> None: ...
    def close(self) -> None: ...


class ipc:
    class RecordBatchStreamReader:
        def __iter__(self) -> Iterator[RecordBatch]: ...

    def open_stream(data: bytes) -> RecordBatchStreamReader: ...
    def new_stream(sink: BufferOutputStream, schema: Any) -> RecordBatchStreamWriter: ...


class types:
    def is_null(dtype: DataType) -> bool: ...
    def is_boolean(dtype: DataType) -> bool: ...
    def is_int8(dtype: DataType) -> bool: ...
    def is_int16(dtype: DataType) -> bool: ...
    def is_int32(dtype: DataType) -> bool: ...
    def is_int64(dtype: DataType) -> bool: ...
    def is_uint8(dtype: DataType) -> bool: ...
    def is_uint16(dtype: DataType) -> bool: ...
    def is_uint32(dtype: DataType) -> bool: ...
    def is_uint64(dtype: DataType) -> bool: ...
    def is_float32(dtype: DataType) -> bool: ...
    def is_float64(dtype: DataType) -> bool: ...
    def is_string(dtype: DataType) -> bool: ...
    def is_large_string(dtype: DataType) -> bool: ...
    def is_binary(dtype: DataType) -> bool: ...
    def is_large_binary(dtype: DataType) -> bool: ...
    def is_fixed_size_binary(dtype: DataType) -> bool: ...
    def is_date32(dtype: DataType) -> bool: ...
    def is_date64(dtype: DataType) -> bool: ...
    def is_time32(dtype: DataType) -> bool: ...
    def is_time64(dtype: DataType) -> bool: ...
    def is_duration(dtype: DataType) -> bool: ...
    def is_timestamp(dtype: DataType) -> bool: ...
    def is_decimal(dtype: DataType) -> bool: ...
    def is_list(dtype: DataType) -> bool: ...
    def is_large_list(dtype: DataType) -> bool: ...
    def is_fixed_size_list(dtype: DataType) -> bool: ...
    def is_struct(dtype: DataType) -> bool: ...


def field(name: str, dtype: DataType, *, nullable: bool = ...) -> Field: ...
def null() -> DataType: ...
def bool_() -> DataType: ...
def int8() -> DataType: ...
def int16() -> DataType: ...
def int32() -> DataType: ...
def int64() -> DataType: ...
def uint8() -> DataType: ...
def uint16() -> DataType: ...
def uint32() -> DataType: ...
def uint64() -> DataType: ...
def float32() -> DataType: ...
def float64() -> DataType: ...
def string() -> DataType: ...
def large_string() -> DataType: ...
def binary(byte_width: int | None = ...) -> DataType: ...
def large_binary() -> DataType: ...
def date32() -> DataType: ...
def date64() -> DataType: ...
def time32(unit: str) -> DataType: ...
def time64(unit: str) -> DataType: ...
def duration(unit: str) -> DataType: ...
def timestamp(unit: str, tz: Optional[str] = ...) -> DataType: ...
def decimal128(precision: int, scale: int) -> DataType: ...
def decimal256(precision: int, scale: int) -> DataType: ...
def list_(field: Field, list_size: int | None = ...) -> DataType: ...
def large_list(field: Field) -> DataType: ...
def fixed_size_list(field: Field, list_size: int) -> DataType: ...
def struct(fields: Iterable[Field]) -> DataType: ...
